services:
  nginx:
    build: .
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./sites/:/etc/nginx/sites-available
      - ./html/:/usr/share/nginx/html
      # - ./ssl/:/etc/nginx/ssl
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot
      - ./certbot/conf/:/etc/letsencrypt/:rw
